<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-11-25T08:58:55 PST" name="Default suite" finished-at="2024-11-25T08:59:13 PST" duration-ms="18017">
    <groups>
    </groups>
    <test started-at="2024-11-25T08:58:55 PST" name="Default test" finished-at="2024-11-25T08:59:13 PST" duration-ms="18017">
      <class name="TestCases.ProblemUser_TestCases">
        <test-method is-config="true" signature="chromeSetup()[pri:0, instance:TestCases.ProblemUser_TestCases@564fabc8]" started-at="2024-11-25T08:58:55 PST" name="chromeSetup" finished-at="2024-11-25T08:59:06 PST" duration-ms="11245" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- chromeSetup -->
        <test-method is-config="true" signature="setup()[pri:0, instance:TestCases.ProblemUser_TestCases@564fabc8]" started-at="2024-11-25T08:59:06 PST" name="setup" finished-at="2024-11-25T08:59:09 PST" duration-ms="3131" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="validateInformation()[pri:0, instance:TestCases.ProblemUser_TestCases@564fabc8]" started-at="2024-11-25T08:59:09 PST" name="validateInformation" finished-at="2024-11-25T08:59:11 PST" duration-ms="1808" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
First name is not match expected [Davinder] but found [u],
Last name is not match expected [Raju] but found [],
Postal Code is not match expected [V3S7N1] but found [Raju]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
First name is not match expected [Davinder] but found [u],
Last name is not match expected [Raju] but found [],
Postal Code is not match expected [V3S7N1] but found [Raju]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at TestCases.ProblemUser_TestCases.validateInformation(ProblemUser_TestCases.java:105)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateInformation -->
        <test-method is-config="true" signature="logoutMethod()[pri:0, instance:TestCases.ProblemUser_TestCases@564fabc8]" started-at="2024-11-25T08:59:11 PST" name="logoutMethod" finished-at="2024-11-25T08:59:13 PST" duration-ms="1106" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutMethod -->
        <test-method is-config="true" signature="quit()[pri:0, instance:TestCases.ProblemUser_TestCases@564fabc8]" started-at="2024-11-25T08:59:13 PST" name="quit" finished-at="2024-11-25T08:59:13 PST" duration-ms="122" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- TestCases.ProblemUser_TestCases -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
